package com.ecommerce.one.ecommerce.mapper;

import com.ecommerce.one.ecommerce.domain.aExample;
import com.ecommerce.one.ecommerce.domain.aKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface aMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    long countByExample(aExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    int deleteByExample(aExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    int deleteByPrimaryKey(aKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    int insert(aKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    int insertSelective(aKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    List<aKey> selectByExample(aExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") aKey record, @Param("example") aExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    int updateByExample(@Param("record") aKey record, @Param("example") aExample example);
}