package com.ecommerce.one.ecommerce.domain;

public class address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ADDRESSID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private Integer addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ORDERID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.CITY
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.PROVINCE
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.STATE
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.STREETNO
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private String streetno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.STREETNAME
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private String streetname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.POSTALCODE
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private Integer postalcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ADDRESSID
     *
     * @return the value of address.ADDRESSID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ADDRESSID
     *
     * @param addressid the value for address.ADDRESSID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ORDERID
     *
     * @return the value of address.ORDERID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ORDERID
     *
     * @param orderid the value for address.ORDERID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.CITY
     *
     * @return the value of address.CITY
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.CITY
     *
     * @param city the value for address.CITY
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.PROVINCE
     *
     * @return the value of address.PROVINCE
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.PROVINCE
     *
     * @param province the value for address.PROVINCE
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.STATE
     *
     * @return the value of address.STATE
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.STATE
     *
     * @param state the value for address.STATE
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.STREETNO
     *
     * @return the value of address.STREETNO
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public String getStreetno() {
        return streetno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.STREETNO
     *
     * @param streetno the value for address.STREETNO
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setStreetno(String streetno) {
        this.streetno = streetno == null ? null : streetno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.STREETNAME
     *
     * @return the value of address.STREETNAME
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public String getStreetname() {
        return streetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.STREETNAME
     *
     * @param streetname the value for address.STREETNAME
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setStreetname(String streetname) {
        this.streetname = streetname == null ? null : streetname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.POSTALCODE
     *
     * @return the value of address.POSTALCODE
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public Integer getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.POSTALCODE
     *
     * @param postalcode the value for address.POSTALCODE
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setPostalcode(Integer postalcode) {
        this.postalcode = postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        address other = (address) that;
        return (this.getAddressid() == null ? other.getAddressid() == null : this.getAddressid().equals(other.getAddressid()))
            && (this.getOrderid() == null ? other.getOrderid() == null : this.getOrderid().equals(other.getOrderid()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getStreetno() == null ? other.getStreetno() == null : this.getStreetno().equals(other.getStreetno()))
            && (this.getStreetname() == null ? other.getStreetname() == null : this.getStreetname().equals(other.getStreetname()))
            && (this.getPostalcode() == null ? other.getPostalcode() == null : this.getPostalcode().equals(other.getPostalcode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAddressid() == null) ? 0 : getAddressid().hashCode());
        result = prime * result + ((getOrderid() == null) ? 0 : getOrderid().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getStreetno() == null) ? 0 : getStreetno().hashCode());
        result = prime * result + ((getStreetname() == null) ? 0 : getStreetname().hashCode());
        result = prime * result + ((getPostalcode() == null) ? 0 : getPostalcode().hashCode());
        return result;
    }
}