package com.ecommerce.one.ecommerce.domain;

public class payment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.PAYMENTID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private Integer paymentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.CUSTOMERIID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private Integer customeriid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.CARD
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private String card;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.WECHAT
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.ALIPAY
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    private String alipay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.PAYMENTID
     *
     * @return the value of payment.PAYMENTID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public Integer getPaymentid() {
        return paymentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.PAYMENTID
     *
     * @param paymentid the value for payment.PAYMENTID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setPaymentid(Integer paymentid) {
        this.paymentid = paymentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.CUSTOMERIID
     *
     * @return the value of payment.CUSTOMERIID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public Integer getCustomeriid() {
        return customeriid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.CUSTOMERIID
     *
     * @param customeriid the value for payment.CUSTOMERIID
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setCustomeriid(Integer customeriid) {
        this.customeriid = customeriid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.CARD
     *
     * @return the value of payment.CARD
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.CARD
     *
     * @param card the value for payment.CARD
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setCard(String card) {
        this.card = card == null ? null : card.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.WECHAT
     *
     * @return the value of payment.WECHAT
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.WECHAT
     *
     * @param wechat the value for payment.WECHAT
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.ALIPAY
     *
     * @return the value of payment.ALIPAY
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public String getAlipay() {
        return alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.ALIPAY
     *
     * @param alipay the value for payment.ALIPAY
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    public void setAlipay(String alipay) {
        this.alipay = alipay == null ? null : alipay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        payment other = (payment) that;
        return (this.getPaymentid() == null ? other.getPaymentid() == null : this.getPaymentid().equals(other.getPaymentid()))
            && (this.getCustomeriid() == null ? other.getCustomeriid() == null : this.getCustomeriid().equals(other.getCustomeriid()))
            && (this.getCard() == null ? other.getCard() == null : this.getCard().equals(other.getCard()))
            && (this.getWechat() == null ? other.getWechat() == null : this.getWechat().equals(other.getWechat()))
            && (this.getAlipay() == null ? other.getAlipay() == null : this.getAlipay().equals(other.getAlipay()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Sun May 24 14:31:24 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPaymentid() == null) ? 0 : getPaymentid().hashCode());
        result = prime * result + ((getCustomeriid() == null) ? 0 : getCustomeriid().hashCode());
        result = prime * result + ((getCard() == null) ? 0 : getCard().hashCode());
        result = prime * result + ((getWechat() == null) ? 0 : getWechat().hashCode());
        result = prime * result + ((getAlipay() == null) ? 0 : getAlipay().hashCode());
        return result;
    }
}