package ndk.banee.spring_estore.mapper;

import java.util.List;
import ndk.banee.spring_estore.domain.customer;
import ndk.banee.spring_estore.domain.customerExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface customerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri May 29 18:59:17 IST 2020
     */
    long countByExample(customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri May 29 18:59:17 IST 2020
     */
    int deleteByExample(customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri May 29 18:59:17 IST 2020
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri May 29 18:59:17 IST 2020
     */
    int insert(customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri May 29 18:59:17 IST 2020
     */
    int insertSelective(customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri May 29 18:59:17 IST 2020
     */
    List<customer> selectByExample(customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri May 29 18:59:17 IST 2020
     */
    customer selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri May 29 18:59:17 IST 2020
     */
    int updateByExampleSelective(@Param("record") customer record, @Param("example") customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri May 29 18:59:17 IST 2020
     */
    int updateByExample(@Param("record") customer record, @Param("example") customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri May 29 18:59:17 IST 2020
     */
    int updateByPrimaryKeySelective(customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri May 29 18:59:17 IST 2020
     */
    int updateByPrimaryKey(customer record);
}
